"""Typed synchronous and asynchronous clients for Hubuum."""

from ._constants import TARGET_SERVER_IMAGE, TARGET_SERVER_VERSION, __version__
from .async_client import AsyncClient
from .client import Client
from .errors import (
    APIError,
    AuthenticationError,
    ConfigurationError,
    ConflictError,
    DecodeError,
    HubuumError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    ResultCardinalityError,
    TransportError,
)
from .models import (
    ApiErrorResponse,
    ClassCreate,
    ClassRelation,
    ClassRelationCreate,
    ClassUpdate,
    Collection,
    CollectionCreate,
    CollectionUpdate,
    Group,
    GroupCreate,
    GroupUpdate,
    HubuumClass,
    HubuumObject,
    ObjectCreate,
    ObjectRelation,
    ObjectRelationCreate,
    ObjectUpdate,
    Task,
    TaskStatus,
    User,
    UserCreate,
    UserUpdate,
)
from .query import Page, Query, QueryFilter
from .types import (
    AccessToken,
    ClassId,
    ClassRelationId,
    CollectionId,
    Credentials,
    FilterOperator,
    GroupId,
    ObjectId,
    ObjectRelationId,
    PrincipalId,
    TaskId,
    UserId,
)

__all__ = [
    "TARGET_SERVER_IMAGE",
    "TARGET_SERVER_VERSION",
    "APIError",
    "AccessToken",
    "ApiErrorResponse",
    "AsyncClient",
    "AuthenticationError",
    "ClassCreate",
    "ClassId",
    "ClassRelation",
    "ClassRelationCreate",
    "ClassRelationId",
    "ClassUpdate",
    "Client",
    "Collection",
    "CollectionCreate",
    "CollectionId",
    "CollectionUpdate",
    "ConfigurationError",
    "ConflictError",
    "Credentials",
    "DecodeError",
    "FilterOperator",
    "Group",
    "GroupCreate",
    "GroupId",
    "GroupUpdate",
    "HubuumClass",
    "HubuumError",
    "HubuumObject",
    "NotFoundError",
    "ObjectCreate",
    "ObjectId",
    "ObjectRelation",
    "ObjectRelationCreate",
    "ObjectRelationId",
    "ObjectUpdate",
    "Page",
    "PermissionDeniedError",
    "PrincipalId",
    "Query",
    "QueryFilter",
    "RateLimitError",
    "ResultCardinalityError",
    "Task",
    "TaskId",
    "TaskStatus",
    "TransportError",
    "User",
    "UserCreate",
    "UserId",
    "UserUpdate",
    "__version__",
]
