"""Immutable Hubuum v0.0.3 OpenAPI operation manifest."""

from __future__ import annotations

from typing import NamedTuple


class OperationSpec(NamedTuple):
    operation_id: str
    method: str
    path: str
    request_media_type: str | None

    @property
    def response_media_types(self) -> tuple[str, ...]:
        """Successful response media types declared by the pinned contract."""
        if self.operation_id in _NO_SUCCESS_RESPONSE_MEDIA:
            return ()
        return _SUCCESS_RESPONSE_MEDIA_OVERRIDES.get(
            self.operation_id,
            ("application/json",),
        )


_OPERATION_ROWS: tuple[tuple[str, str, str, str | None], ...] = (
    ("deleteApiV0MetaLoginRateLimit", "DELETE", "/api/v0/meta/login-rate-limit", None),
    ("deleteApiV0MetaLoginRateLimitById", "DELETE", "/api/v0/meta/login-rate-limit/{id}", None),
    ("deleteApiV1ClassesByClassId", "DELETE", "/api/v1/classes/{class_id}", None),
    (
        "deleteApiV1ClassesByClassIdByFromObjectIdRelationsByToClassIdByToObjectId",
        "DELETE",
        "/api/v1/classes/{class_id}/{from_object_id}/relations/{to_class_id}/{to_object_id}",
        None,
    ),
    (
        "deleteApiV1ClassesByClassIdByObjectId",
        "DELETE",
        "/api/v1/classes/{class_id}/{object_id}",
        None,
    ),
    (
        "deleteApiV1ClassesByClassIdComputedFieldsByFieldId",
        "DELETE",
        "/api/v1/classes/{class_id}/computed-fields/{field_id}",
        None,
    ),
    (
        "deleteApiV1ClassesByClassIdRelationsByRelationId",
        "DELETE",
        "/api/v1/classes/{class_id}/relations/{relation_id}",
        None,
    ),
    (
        "deleteApiV1ClassesByNameByClassName",
        "DELETE",
        "/api/v1/classes/by-name/{class_name}",
        None,
    ),
    (
        "deleteApiV1ClassesByNameByClassNameObjectsByNameByObjectName",
        "DELETE",
        "/api/v1/classes/by-name/{class_name}/objects/by-name/{object_name}",
        None,
    ),
    (
        "deleteApiV1CollectionsByCollectionId",
        "DELETE",
        "/api/v1/collections/{collection_id}",
        None,
    ),
    (
        "deleteApiV1CollectionsByCollectionIdEventSubscriptionsBySubscriptionId",
        "DELETE",
        "/api/v1/collections/{collection_id}/event-subscriptions/{subscription_id}",
        None,
    ),
    (
        "deleteApiV1CollectionsByCollectionIdPermissionsGroupByGroupId",
        "DELETE",
        "/api/v1/collections/{collection_id}/permissions/group/{group_id}",
        None,
    ),
    (
        "deleteApiV1CollectionsByCollectionIdPermissionsGroupByGroupIdByPermission",
        "DELETE",
        "/api/v1/collections/{collection_id}/permissions/group/{group_id}/{permission}",
        None,
    ),
    ("deleteApiV1EventSinksBySinkId", "DELETE", "/api/v1/event-sinks/{sink_id}", None),
    (
        "deleteApiV1ExportTemplatesByTemplateId",
        "DELETE",
        "/api/v1/export-templates/{template_id}",
        None,
    ),
    ("deleteApiV1IamGroupsByGroupId", "DELETE", "/api/v1/iam/groups/{group_id}", None),
    (
        "deleteApiV1IamGroupsByGroupIdMembersByPrincipalId",
        "DELETE",
        "/api/v1/iam/groups/{group_id}/members/{principal_id}",
        None,
    ),
    (
        "deleteApiV1IamMeComputedFieldsByFieldId",
        "DELETE",
        "/api/v1/iam/me/computed-fields/{field_id}",
        None,
    ),
    ("deleteApiV1IamMeSettings", "DELETE", "/api/v1/iam/me/settings", None),
    (
        "deleteApiV1IamPrincipalsByPrincipalIdSettings",
        "DELETE",
        "/api/v1/iam/principals/{principal_id}/settings",
        None,
    ),
    (
        "deleteApiV1IamServiceAccountsByServiceAccountId",
        "DELETE",
        "/api/v1/iam/service-accounts/{service_account_id}",
        None,
    ),
    ("deleteApiV1IamUsersByUserId", "DELETE", "/api/v1/iam/users/{user_id}", None),
    (
        "deleteApiV1RelationsClassesByRelationId",
        "DELETE",
        "/api/v1/relations/classes/{relation_id}",
        None,
    ),
    (
        "deleteApiV1RelationsObjectsByRelationId",
        "DELETE",
        "/api/v1/relations/objects/{relation_id}",
        None,
    ),
    (
        "deleteApiV1RemoteTargetsByTargetId",
        "DELETE",
        "/api/v1/remote-targets/{target_id}",
        None,
    ),
    ("getApiV0AuthProviders", "GET", "/api/v0/auth/providers", None),
    ("getApiV0AuthValidate", "GET", "/api/v0/auth/validate", None),
    ("getApiV0MetaCounts", "GET", "/api/v0/meta/counts", None),
    ("getApiV0MetaDb", "GET", "/api/v0/meta/db", None),
    ("getApiV0MetaLoginRateLimit", "GET", "/api/v0/meta/login-rate-limit", None),
    ("getApiV0MetaTasks", "GET", "/api/v0/meta/tasks", None),
    ("getApiV1AdminConfig", "GET", "/api/v1/admin/config", None),
    ("getApiV1BackupsByTaskId", "GET", "/api/v1/backups/{task_id}", None),
    ("getApiV1BackupsByTaskIdOutput", "GET", "/api/v1/backups/{task_id}/output", None),
    ("getApiV1Classes", "GET", "/api/v1/classes", None),
    ("getApiV1ClassesByClassId", "GET", "/api/v1/classes/{class_id}", None),
    (
        "getApiV1ClassesByClassIdByFromObjectIdRelationsByToClassIdByToObjectId",
        "GET",
        "/api/v1/classes/{class_id}/{from_object_id}/relations/{to_class_id}/{to_object_id}",
        None,
    ),
    (
        "getApiV1ClassesByClassIdByObjectId",
        "GET",
        "/api/v1/classes/{class_id}/{object_id}",
        None,
    ),
    (
        "getApiV1ClassesByClassIdByObjectIdEvents",
        "GET",
        "/api/v1/classes/{class_id}/{object_id}/events",
        None,
    ),
    (
        "getApiV1ClassesByClassIdByObjectIdHistory",
        "GET",
        "/api/v1/classes/{class_id}/{object_id}/history",
        None,
    ),
    (
        "getApiV1ClassesByClassIdByObjectIdHistoryAsOf",
        "GET",
        "/api/v1/classes/{class_id}/{object_id}/history/as-of",
        None,
    ),
    (
        "getApiV1ClassesByClassIdComputedFields",
        "GET",
        "/api/v1/classes/{class_id}/computed-fields",
        None,
    ),
    ("getApiV1ClassesByClassIdEvents", "GET", "/api/v1/classes/{class_id}/events", None),
    ("getApiV1ClassesByClassIdHistory", "GET", "/api/v1/classes/{class_id}/history", None),
    (
        "getApiV1ClassesByClassIdHistoryAsOf",
        "GET",
        "/api/v1/classes/{class_id}/history/as-of",
        None,
    ),
    (
        "getApiV1ClassesByClassIdObjectAggregates",
        "GET",
        "/api/v1/classes/{class_id}/object-aggregates",
        None,
    ),
    (
        "getApiV1ClassesByClassIdObjectsByObjectIdRelatedGraph",
        "GET",
        "/api/v1/classes/{class_id}/objects/{object_id}/related/graph",
        None,
    ),
    (
        "getApiV1ClassesByClassIdObjectsByObjectIdRelatedObjects",
        "GET",
        "/api/v1/classes/{class_id}/objects/{object_id}/related/objects",
        None,
    ),
    (
        "getApiV1ClassesByClassIdObjectsByObjectIdRelatedRelations",
        "GET",
        "/api/v1/classes/{class_id}/objects/{object_id}/related/relations",
        None,
    ),
    (
        "getApiV1ClassesByClassIdPermissions",
        "GET",
        "/api/v1/classes/{class_id}/permissions",
        None,
    ),
    (
        "getApiV1ClassesByClassIdRelatedClasses",
        "GET",
        "/api/v1/classes/{class_id}/related/classes",
        None,
    ),
    (
        "getApiV1ClassesByClassIdRelatedGraph",
        "GET",
        "/api/v1/classes/{class_id}/related/graph",
        None,
    ),
    (
        "getApiV1ClassesByClassIdRelatedRelations",
        "GET",
        "/api/v1/classes/{class_id}/related/relations",
        None,
    ),
    ("getApiV1ClassesByClassIdTrailing", "GET", "/api/v1/classes/{class_id}/", None),
    (
        "getApiV1ClassesByNameByClassName",
        "GET",
        "/api/v1/classes/by-name/{class_name}",
        None,
    ),
    (
        "getApiV1ClassesByNameByClassNameObjectAggregates",
        "GET",
        "/api/v1/classes/by-name/{class_name}/object-aggregates",
        None,
    ),
    (
        "getApiV1ClassesByNameByClassNameObjects",
        "GET",
        "/api/v1/classes/by-name/{class_name}/objects",
        None,
    ),
    (
        "getApiV1ClassesByNameByClassNameObjectsByNameByObjectName",
        "GET",
        "/api/v1/classes/by-name/{class_name}/objects/by-name/{object_name}",
        None,
    ),
    (
        "getApiV1ClassesByNameByClassNameObjectsByNameByObjectNameRelatedGraph",
        "GET",
        "/api/v1/classes/by-name/{class_name}/objects/by-name/{object_name}/related/graph",
        None,
    ),
    (
        "getApiV1ClassesByNameByClassNameObjectsByNameByObjectNameRelatedObjects",
        "GET",
        "/api/v1/classes/by-name/{class_name}/objects/by-name/{object_name}/related/objects",
        None,
    ),
    (
        "getApiV1ClassesByNameByClassNameObjectsByNameByObjectNameRelatedRelations",
        "GET",
        "/api/v1/classes/by-name/{class_name}/objects/by-name/{object_name}/related/relations",
        None,
    ),
    (
        "getApiV1ClassesByNameByClassNamePermissions",
        "GET",
        "/api/v1/classes/by-name/{class_name}/permissions",
        None,
    ),
    (
        "getApiV1ClassesByNameByClassNameRelatedClasses",
        "GET",
        "/api/v1/classes/by-name/{class_name}/related/classes",
        None,
    ),
    (
        "getApiV1ClassesByNameByClassNameRelatedGraph",
        "GET",
        "/api/v1/classes/by-name/{class_name}/related/graph",
        None,
    ),
    (
        "getApiV1ClassesByNameByClassNameRelatedRelations",
        "GET",
        "/api/v1/classes/by-name/{class_name}/related/relations",
        None,
    ),
    ("getApiV1Collections", "GET", "/api/v1/collections", None),
    (
        "getApiV1CollectionsByCollectionId",
        "GET",
        "/api/v1/collections/{collection_id}",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdAncestors",
        "GET",
        "/api/v1/collections/{collection_id}/ancestors",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdChildren",
        "GET",
        "/api/v1/collections/{collection_id}/children",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdEventSubscriptions",
        "GET",
        "/api/v1/collections/{collection_id}/event-subscriptions",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdEventSubscriptionsBySubscriptionId",
        "GET",
        "/api/v1/collections/{collection_id}/event-subscriptions/{subscription_id}",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdEvents",
        "GET",
        "/api/v1/collections/{collection_id}/events",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdHasPermissionsByPermission",
        "GET",
        "/api/v1/collections/{collection_id}/has_permissions/{permission}",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdHistory",
        "GET",
        "/api/v1/collections/{collection_id}/history",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdHistoryAsOf",
        "GET",
        "/api/v1/collections/{collection_id}/history/as-of",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdPermissions",
        "GET",
        "/api/v1/collections/{collection_id}/permissions",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdPermissionsEffectiveGroupByGroupId",
        "GET",
        "/api/v1/collections/{collection_id}/permissions/effective/group/{group_id}",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdPermissionsEffectivePrincipalByPrincipalId",
        "GET",
        "/api/v1/collections/{collection_id}/permissions/effective/principal/{principal_id}",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdPermissionsGroupByGroupId",
        "GET",
        "/api/v1/collections/{collection_id}/permissions/group/{group_id}",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdPermissionsGroupByGroupIdByPermission",
        "GET",
        "/api/v1/collections/{collection_id}/permissions/group/{group_id}/{permission}",
        None,
    ),
    (
        "getApiV1CollectionsByCollectionIdPermissionsPrincipalByPrincipalId",
        "GET",
        "/api/v1/collections/{collection_id}/permissions/principal/{principal_id}",
        None,
    ),
    ("getApiV1Config", "GET", "/api/v1/config", None),
    ("getApiV1EventDeliveries", "GET", "/api/v1/event-deliveries", None),
    (
        "getApiV1EventDeliveriesByDeliveryId",
        "GET",
        "/api/v1/event-deliveries/{delivery_id}",
        None,
    ),
    ("getApiV1EventDeliveriesHealth", "GET", "/api/v1/event-deliveries/health", None),
    ("getApiV1EventSinks", "GET", "/api/v1/event-sinks", None),
    ("getApiV1EventSinksBySinkId", "GET", "/api/v1/event-sinks/{sink_id}", None),
    ("getApiV1Events", "GET", "/api/v1/events", None),
    ("getApiV1ExportTemplates", "GET", "/api/v1/export-templates", None),
    (
        "getApiV1ExportTemplatesByTemplateId",
        "GET",
        "/api/v1/export-templates/{template_id}",
        None,
    ),
    (
        "getApiV1ExportTemplatesByTemplateIdEvents",
        "GET",
        "/api/v1/export-templates/{template_id}/events",
        None,
    ),
    (
        "getApiV1ExportTemplatesByTemplateIdHistory",
        "GET",
        "/api/v1/export-templates/{template_id}/history",
        None,
    ),
    (
        "getApiV1ExportTemplatesByTemplateIdHistoryAsOf",
        "GET",
        "/api/v1/export-templates/{template_id}/history/as-of",
        None,
    ),
    ("getApiV1ExportsByTaskId", "GET", "/api/v1/exports/{task_id}", None),
    ("getApiV1ExportsByTaskIdOutput", "GET", "/api/v1/exports/{task_id}/output", None),
    ("getApiV1IamGroups", "GET", "/api/v1/iam/groups", None),
    ("getApiV1IamGroupsByGroupId", "GET", "/api/v1/iam/groups/{group_id}", None),
    (
        "getApiV1IamGroupsByGroupIdEvents",
        "GET",
        "/api/v1/iam/groups/{group_id}/events",
        None,
    ),
    (
        "getApiV1IamGroupsByGroupIdMembers",
        "GET",
        "/api/v1/iam/groups/{group_id}/members",
        None,
    ),
    ("getApiV1IamMe", "GET", "/api/v1/iam/me", None),
    ("getApiV1IamMeComputedFields", "GET", "/api/v1/iam/me/computed-fields", None),
    ("getApiV1IamMeGroups", "GET", "/api/v1/iam/me/groups", None),
    ("getApiV1IamMePermissions", "GET", "/api/v1/iam/me/permissions", None),
    ("getApiV1IamMeSettings", "GET", "/api/v1/iam/me/settings", None),
    ("getApiV1IamMeTokens", "GET", "/api/v1/iam/me/tokens", None),
    (
        "getApiV1IamPrincipalsByPrincipalIdGroups",
        "GET",
        "/api/v1/iam/principals/{principal_id}/groups",
        None,
    ),
    (
        "getApiV1IamPrincipalsByPrincipalIdPermissions",
        "GET",
        "/api/v1/iam/principals/{principal_id}/permissions",
        None,
    ),
    (
        "getApiV1IamPrincipalsByPrincipalIdSettings",
        "GET",
        "/api/v1/iam/principals/{principal_id}/settings",
        None,
    ),
    (
        "getApiV1IamPrincipalsByPrincipalIdTokens",
        "GET",
        "/api/v1/iam/principals/{principal_id}/tokens",
        None,
    ),
    ("getApiV1IamServiceAccounts", "GET", "/api/v1/iam/service-accounts", None),
    (
        "getApiV1IamServiceAccountsByServiceAccountId",
        "GET",
        "/api/v1/iam/service-accounts/{service_account_id}",
        None,
    ),
    ("getApiV1IamUsers", "GET", "/api/v1/iam/users", None),
    ("getApiV1IamUsersByUserId", "GET", "/api/v1/iam/users/{user_id}", None),
    (
        "getApiV1IamUsersByUserIdEvents",
        "GET",
        "/api/v1/iam/users/{user_id}/events",
        None,
    ),
    ("getApiV1ImportsByTaskId", "GET", "/api/v1/imports/{task_id}", None),
    ("getApiV1ImportsByTaskIdResults", "GET", "/api/v1/imports/{task_id}/results", None),
    ("getApiV1RelationsClasses", "GET", "/api/v1/relations/classes", None),
    (
        "getApiV1RelationsClassesByRelationId",
        "GET",
        "/api/v1/relations/classes/{relation_id}",
        None,
    ),
    ("getApiV1RelationsObjects", "GET", "/api/v1/relations/objects", None),
    (
        "getApiV1RelationsObjectsByRelationId",
        "GET",
        "/api/v1/relations/objects/{relation_id}",
        None,
    ),
    ("getApiV1RemoteTargets", "GET", "/api/v1/remote-targets", None),
    (
        "getApiV1RemoteTargetsByRemoteTargetIdHistory",
        "GET",
        "/api/v1/remote-targets/{remote_target_id}/history",
        None,
    ),
    (
        "getApiV1RemoteTargetsByRemoteTargetIdHistoryAsOf",
        "GET",
        "/api/v1/remote-targets/{remote_target_id}/history/as-of",
        None,
    ),
    (
        "getApiV1RemoteTargetsByTargetId",
        "GET",
        "/api/v1/remote-targets/{target_id}",
        None,
    ),
    (
        "getApiV1RemoteTargetsByTargetIdEvents",
        "GET",
        "/api/v1/remote-targets/{target_id}/events",
        None,
    ),
    (
        "getApiV1RestoresByRestoreIdStatus",
        "GET",
        "/api/v1/restores/{restore_id}/status",
        None,
    ),
    ("getApiV1Search", "GET", "/api/v1/search", None),
    ("getApiV1SearchStream", "GET", "/api/v1/search/stream", None),
    ("getApiV1Tasks", "GET", "/api/v1/tasks", None),
    ("getApiV1TasksByTaskId", "GET", "/api/v1/tasks/{task_id}", None),
    ("getApiV1TasksByTaskIdEvents", "GET", "/api/v1/tasks/{task_id}/events", None),
    ("getHealthz", "GET", "/healthz", None),
    ("getReadyz", "GET", "/readyz", None),
    (
        "patchApiV1ClassesByClassId",
        "PATCH",
        "/api/v1/classes/{class_id}",
        "application/json",
    ),
    (
        "patchApiV1ClassesByClassIdByObjectId",
        "PATCH",
        "/api/v1/classes/{class_id}/{object_id}",
        "application/json",
    ),
    (
        "patchApiV1ClassesByClassIdByObjectIdData",
        "PATCH",
        "/api/v1/classes/{class_id}/{object_id}/data",
        "application/json-patch+json",
    ),
    (
        "patchApiV1ClassesByClassIdComputedFieldsByFieldId",
        "PATCH",
        "/api/v1/classes/{class_id}/computed-fields/{field_id}",
        "application/json",
    ),
    (
        "patchApiV1ClassesByNameByClassName",
        "PATCH",
        "/api/v1/classes/by-name/{class_name}",
        "application/json",
    ),
    (
        "patchApiV1ClassesByNameByClassNameObjectsByNameByObjectName",
        "PATCH",
        "/api/v1/classes/by-name/{class_name}/objects/by-name/{object_name}",
        "application/json",
    ),
    (
        "patchApiV1ClassesByNameByClassNameObjectsByNameByObjectNameData",
        "PATCH",
        "/api/v1/classes/by-name/{class_name}/objects/by-name/{object_name}/data",
        "application/json-patch+json",
    ),
    (
        "patchApiV1CollectionsByCollectionId",
        "PATCH",
        "/api/v1/collections/{collection_id}",
        "application/json",
    ),
    (
        "patchApiV1CollectionsByCollectionIdEventSubscriptionsBySubscriptionId",
        "PATCH",
        "/api/v1/collections/{collection_id}/event-subscriptions/{subscription_id}",
        "application/json",
    ),
    (
        "patchApiV1EventSinksBySinkId",
        "PATCH",
        "/api/v1/event-sinks/{sink_id}",
        "application/json",
    ),
    (
        "patchApiV1ExportTemplatesByTemplateId",
        "PATCH",
        "/api/v1/export-templates/{template_id}",
        "application/json",
    ),
    (
        "patchApiV1IamGroupsByGroupId",
        "PATCH",
        "/api/v1/iam/groups/{group_id}",
        "application/json",
    ),
    (
        "patchApiV1IamMeComputedFieldsByFieldId",
        "PATCH",
        "/api/v1/iam/me/computed-fields/{field_id}",
        "application/json",
    ),
    (
        "patchApiV1IamMeSettings",
        "PATCH",
        "/api/v1/iam/me/settings",
        "application/json",
    ),
    (
        "patchApiV1IamPrincipalsByPrincipalIdSettings",
        "PATCH",
        "/api/v1/iam/principals/{principal_id}/settings",
        "application/json",
    ),
    (
        "patchApiV1IamServiceAccountsByServiceAccountId",
        "PATCH",
        "/api/v1/iam/service-accounts/{service_account_id}",
        "application/json",
    ),
    (
        "patchApiV1IamUsersByUserId",
        "PATCH",
        "/api/v1/iam/users/{user_id}",
        "application/json",
    ),
    (
        "patchApiV1RemoteTargetsByTargetId",
        "PATCH",
        "/api/v1/remote-targets/{target_id}",
        "application/json",
    ),
    ("postApiV0AuthLogin", "POST", "/api/v0/auth/login", "application/json"),
    ("postApiV0AuthLogout", "POST", "/api/v0/auth/logout", None),
    ("postApiV0AuthLogoutAll", "POST", "/api/v0/auth/logout_all", None),
    ("postApiV0AuthLogoutToken", "POST", "/api/v0/auth/logout/token", "application/json"),
    ("postApiV0AuthLogoutUidByUserId", "POST", "/api/v0/auth/logout/uid/{user_id}", None),
    ("postApiV1Backups", "POST", "/api/v1/backups", "application/json"),
    ("postApiV1Classes", "POST", "/api/v1/classes", "application/json"),
    (
        "postApiV1ClassesByClassIdByFromObjectIdRelationsByToClassIdByToObjectId",
        "POST",
        "/api/v1/classes/{class_id}/{from_object_id}/relations/{to_class_id}/{to_object_id}",
        None,
    ),
    (
        "postApiV1ClassesByClassIdComputedFields",
        "POST",
        "/api/v1/classes/{class_id}/computed-fields",
        "application/json",
    ),
    (
        "postApiV1ClassesByClassIdComputedFieldsPreview",
        "POST",
        "/api/v1/classes/{class_id}/computed-fields/preview",
        "application/json",
    ),
    (
        "postApiV1ClassesByClassIdComputedFieldsRebuild",
        "POST",
        "/api/v1/classes/{class_id}/computed-fields/rebuild",
        None,
    ),
    (
        "postApiV1ClassesByClassIdRelations",
        "POST",
        "/api/v1/classes/{class_id}/relations",
        "application/json",
    ),
    (
        "postApiV1ClassesByClassIdTrailing",
        "POST",
        "/api/v1/classes/{class_id}/",
        "application/json",
    ),
    (
        "postApiV1ClassesByNameByClassNameObjects",
        "POST",
        "/api/v1/classes/by-name/{class_name}/objects",
        "application/json",
    ),
    ("postApiV1Collections", "POST", "/api/v1/collections", "application/json"),
    (
        "postApiV1CollectionsByCollectionIdEventSubscriptions",
        "POST",
        "/api/v1/collections/{collection_id}/event-subscriptions",
        "application/json",
    ),
    (
        "postApiV1CollectionsByCollectionIdPermissionsGroupByGroupId",
        "POST",
        "/api/v1/collections/{collection_id}/permissions/group/{group_id}",
        "application/json",
    ),
    (
        "postApiV1CollectionsByCollectionIdPermissionsGroupByGroupIdByPermission",
        "POST",
        "/api/v1/collections/{collection_id}/permissions/group/{group_id}/{permission}",
        None,
    ),
    (
        "postApiV1EventDeliveriesByDeliveryIdDead",
        "POST",
        "/api/v1/event-deliveries/{delivery_id}/dead",
        None,
    ),
    (
        "postApiV1EventDeliveriesByDeliveryIdRetry",
        "POST",
        "/api/v1/event-deliveries/{delivery_id}/retry",
        None,
    ),
    ("postApiV1EventSinks", "POST", "/api/v1/event-sinks", "application/json"),
    (
        "postApiV1ExportTemplates",
        "POST",
        "/api/v1/export-templates",
        "application/json",
    ),
    (
        "postApiV1ExportTemplatesByTemplateIdExports",
        "POST",
        "/api/v1/export-templates/{template_id}/exports",
        "application/json",
    ),
    ("postApiV1Exports", "POST", "/api/v1/exports", "application/json"),
    ("postApiV1IamGroups", "POST", "/api/v1/iam/groups", "application/json"),
    (
        "postApiV1IamGroupsByGroupIdMembersByPrincipalId",
        "POST",
        "/api/v1/iam/groups/{group_id}/members/{principal_id}",
        None,
    ),
    (
        "postApiV1IamMeComputedFields",
        "POST",
        "/api/v1/iam/me/computed-fields",
        "application/json",
    ),
    (
        "postApiV1IamMeComputedFieldsPreview",
        "POST",
        "/api/v1/iam/me/computed-fields/preview",
        "application/json",
    ),
    (
        "postApiV1IamPrincipalsByPrincipalIdTokens",
        "POST",
        "/api/v1/iam/principals/{principal_id}/tokens",
        "application/json",
    ),
    (
        "postApiV1IamPrincipalsByPrincipalIdTokensByTokenIdRevoke",
        "POST",
        "/api/v1/iam/principals/{principal_id}/tokens/{token_id}/revoke",
        None,
    ),
    (
        "postApiV1IamServiceAccounts",
        "POST",
        "/api/v1/iam/service-accounts",
        "application/json",
    ),
    (
        "postApiV1IamServiceAccountsByServiceAccountIdDisable",
        "POST",
        "/api/v1/iam/service-accounts/{service_account_id}/disable",
        None,
    ),
    ("postApiV1IamUsers", "POST", "/api/v1/iam/users", "application/json"),
    (
        "postApiV1IamUsersByUserIdAnonymize",
        "POST",
        "/api/v1/iam/users/{user_id}/anonymize",
        None,
    ),
    ("postApiV1Imports", "POST", "/api/v1/imports", "application/json"),
    (
        "postApiV1RelationsClasses",
        "POST",
        "/api/v1/relations/classes",
        "application/json",
    ),
    (
        "postApiV1RelationsObjects",
        "POST",
        "/api/v1/relations/objects",
        "application/json",
    ),
    (
        "postApiV1RemoteTargets",
        "POST",
        "/api/v1/remote-targets",
        "application/json",
    ),
    (
        "postApiV1RemoteTargetsByTargetIdInvoke",
        "POST",
        "/api/v1/remote-targets/{target_id}/invoke",
        "application/json",
    ),
    ("postApiV1Restores", "POST", "/api/v1/restores", "application/json"),
    (
        "postApiV1RestoresByRestoreIdConfirm",
        "POST",
        "/api/v1/restores/{restore_id}/confirm",
        "application/json",
    ),
    (
        "putApiV1CollectionsByCollectionIdParent",
        "PUT",
        "/api/v1/collections/{collection_id}/parent",
        "application/json",
    ),
    (
        "putApiV1CollectionsByCollectionIdPermissionsGroupByGroupId",
        "PUT",
        "/api/v1/collections/{collection_id}/permissions/group/{group_id}",
        "application/json",
    ),
    ("putApiV1IamMeSettings", "PUT", "/api/v1/iam/me/settings", "application/json"),
    (
        "putApiV1IamPrincipalsByPrincipalIdSettings",
        "PUT",
        "/api/v1/iam/principals/{principal_id}/settings",
        "application/json",
    ),
)

OPERATIONS = {
    operation_id: OperationSpec(operation_id, method, path, request_media_type)
    for operation_id, method, path, request_media_type in _OPERATION_ROWS
}
_NO_SUCCESS_RESPONSE_MEDIA = frozenset(
    {
        "deleteApiV1ClassesByClassId",
        "deleteApiV1ClassesByClassIdByFromObjectIdRelationsByToClassIdByToObjectId",
        "deleteApiV1ClassesByClassIdByObjectId",
        "deleteApiV1ClassesByClassIdRelationsByRelationId",
        "deleteApiV1ClassesByNameByClassName",
        "deleteApiV1ClassesByNameByClassNameObjectsByNameByObjectName",
        "deleteApiV1CollectionsByCollectionId",
        "deleteApiV1CollectionsByCollectionIdEventSubscriptionsBySubscriptionId",
        "deleteApiV1CollectionsByCollectionIdPermissionsGroupByGroupId",
        "deleteApiV1CollectionsByCollectionIdPermissionsGroupByGroupIdByPermission",
        "deleteApiV1EventSinksBySinkId",
        "deleteApiV1ExportTemplatesByTemplateId",
        "deleteApiV1IamGroupsByGroupId",
        "deleteApiV1IamGroupsByGroupIdMembersByPrincipalId",
        "deleteApiV1IamMeComputedFieldsByFieldId",
        "deleteApiV1IamMeSettings",
        "deleteApiV1IamPrincipalsByPrincipalIdSettings",
        "deleteApiV1IamServiceAccountsByServiceAccountId",
        "deleteApiV1IamUsersByUserId",
        "deleteApiV1RelationsClassesByRelationId",
        "deleteApiV1RelationsObjectsByRelationId",
        "deleteApiV1RemoteTargetsByTargetId",
        "getApiV1CollectionsByCollectionIdPermissionsGroupByGroupIdByPermission",
        "getApiV1SearchStream",
        "postApiV1CollectionsByCollectionIdPermissionsGroupByGroupId",
        "postApiV1CollectionsByCollectionIdPermissionsGroupByGroupIdByPermission",
        "postApiV1IamGroupsByGroupIdMembersByPrincipalId",
        "postApiV1IamPrincipalsByPrincipalIdTokensByTokenIdRevoke",
        "postApiV1IamUsersByUserIdAnonymize",
        "putApiV1CollectionsByCollectionIdPermissionsGroupByGroupId",
    }
)
_SUCCESS_RESPONSE_MEDIA_OVERRIDES = {
    "getApiV1ExportsByTaskIdOutput": (
        "application/json",
        "text/csv",
        "text/html",
        "text/plain",
    )
}
SUPPORTED_OPERATIONS = frozenset((item.method.lower(), item.path) for item in OPERATIONS.values())
PUBLIC_OPERATION_IDS = frozenset(
    {
        "getApiV0AuthProviders",
        "getApiV1Config",
        "getHealthz",
        "getReadyz",
        "postApiV0AuthLogin",
    }
)
STREAMING_OPERATION_IDS = frozenset({"getApiV1SearchStream"})
